### ISSUE TITLE
AssertionError during question generation.

### ISSUE THREAD

**Issue by Krak91** [patil-suraj/question_generation#30]
Hello @patil-suraj, 

I get the following assertion error:

Code:
```
gen = pipeline("question-generation", model='valhalla/t5-base-qg-hl', ans_model='valhalla/t5-base-qa-qg-hl')
qa = gen('Direct calls or provocation to audiences to commit criminal acts should be challenged.')
```

Error:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File ".../teaching.py", line 167, in <module>
    qa = gen('Direct calls or provocation to audiences to commit criminal acts should be challenged.')
  File "...\question_generation\pipelines.py", line 63, in __call__
    questions = self._generate_questions(qg_inputs)
  File "...\question_generation\pipelines.py", line 68, in _generate_questions
    inputs = self._tokenize(inputs, padding=True, truncation=True)
  File "...\question_generation\pipelines.py", line 110, in _tokenize
    return_tensors="pt"
  File "...\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1832, in batch_encode_plus
    **kwargs,
  File "...\venv\lib\site-packages\transformers\tokenization_utils.py", line 554, in _batch_encode_plus
    verbose=verbose,
  File "...\venv\lib\site-packages\transformers\tokenization_utils.py", line 616, in _batch_prepare_for_model
    return_attention_mask=return_attention_mask,
  File "...\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1912, in pad
    "You should supply an encoding or a list of encodings to this method. "
AssertionError: You should supply an encoding or a list of encodings to this method. An encoding is the output of one the encoding methods of the tokenizer, i.e. __call__/encode_plus/batch_encode_plus.

**Comment by patil-suraj** [comment]
hi @Krak91 ,

I tried this and it worked for me 
```
gen = pipeline("question-generation", model='valhalla/t5-base-qg-hl', ans_model='valhalla/t5-base-qa-qg-hl')
qa = gen('Direct calls or provocation to audiences to commit criminal acts should be challenged.')
```

are you still facing this issue ?

**Comment by Krak91** [comment]
Yes. The models in general produce very good questions, it's actually very impressive but this specific text brought up this error. I can't figure out what's causing it.. I've also made sure the text is in utf-8.

**Comment by Krak91** [comment]
Hi, @patil-suraj 
Any update on this?

**Comment by HenryJunW** [comment]
Got the same problem, 'AssertionError: You should supply an encoding or a list of encodings to this method. An encoding is the output of one the encoding methods of the tokenizer, i.e. __call__/encode_plus/batch_encode_plus.'

Any work around? Thanks!
