### ISSUE TITLE
model.generate on tensorflow converted model is not working

### ISSUE THREAD

**Issue by paniabhisek** [patil-suraj/question_generation#36]
### Conversion
**model**: https://huggingface.co/valhalla/t5-small-e2e-qg
**Script**: https://github.com/huggingface/transformers/blob/master/src/transformers/convert_pytorch_checkpoint_to_tf2.py

Instead of `tf_model.save_weights(tf_dump_path, save_format="h5")`, I used `tf_model.save_pretrained`.

When I used the following script for inference:

    from transformers import T5Tokenizer, TFT5ForConditionalGeneration

    tokenizer = T5Tokenizer.from_pretrained('valhalla/t5-small-e2e-qg')
    model = TFT5ForConditionalGeneration.from_pretrained('save-pretrained')

    inputs = tokenizer.batch_encode_plus(['question-generation: Python is a programming language. Created by Guido van Rossum and first released in 1991.'], max_length=64, add_special_tokens=True, truncation=True, padding=False, pad_to_max_length=False, return_tensors="tf")

    model.generate(input_ids=inputs['input_ids'],
               #attention_mask=inputs['attention_mask'],
               **{"max_length": 64, "num_beams": 4, "length_penalty": 1.5, "no_repeat_ngram_size": 3, "early_stopping": True,})

I'm encountering the error:

	Traceback (most recent call last):
	  File "e2e-qg.py", line 10, in <module>
		model.generate(input_ids=inputs['input_ids'],
	  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 909, in generate
		use_cache=use_cache,
	  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 951, in _generate_no_beam_search
		outputs = self(**model_inputs)
	  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
		outputs = call_fn(inputs, *args, **kwargs)
	  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_tf_t5.py", line 1148, in call
		output_hidden_states=output_hidden_states,
	  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
		outputs = call_fn(inputs, *args, **kwargs)
	  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_tf_t5.py", line 616, in call
		mask_seq_length = shape_list(past_key_value_states[0][0])[2] + seq_length
	IndexError: list index out of range

Let me know where is the issue or you have any workaround for the same?

**Comment by paniabhisek** [comment]
Without intermediate conversion using [transformer-script](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_pytorch_checkpoint_to_tf2.py), I'm able to get result using the following method:

    model = TFT5ForConditionalGeneration.from_pretrained('valhalla/t5-small-e2e-qg', from_pt=True)

Don't know if there is bug in conversion script. Closing for now.
